# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt install python3-pip python3-setuptools python3-dev
        python3 -m pip install --upgrade pip
        pip3 install empy

    - name: Download sugar and install 
      run: |
        sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
        for module in sugar{-datastore,-artwork,-toolkit,-toolkit-gtk3,}; do
            git clone https://github.com/sugarlabs/$module.git
        done
        sudo apt update
        for module in sugar{-datastore,-artwork,-toolkit-gtk3,}; do
            sudo apt build-dep $module
        done
        sudo apt install python{,3}-six python3-empy
        for module in sugar{-artwork,-toolkit-gtk3,-datastore,}; do
            cd $module
            ./autogen.sh --with-python3 --prefix=/usr
            make
            sudo make install
            cd ..
        done
        sudo mkdir -p /usr/lib/python3.6/dist-packages
        sudo cp -r /usr/lib/python3.6/site-packages/sugar3 /usr/lib/python3.6/dist-packages/.
        sudo cp -r /usr/lib/python3.6/site-packages/jarabe /usr/lib/python3.6/dist-packages/.
        sudo cp -r /usr/lib/python3.6/site-packages/carquinyol /usr/lib/python3.6/dist-packages/.
        echo 'Sugar Installed'
        echo $(which sugar-activity)
        
    - name: Test Sugar

      run: |
        echo $PYTHONPATH
        echo $PATH
        
        python3 -c "import sugar3"
    - name: Clone 100 activities
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        export PATH=$PATH:$SUGAR_PATH
        mkdir activities
        cd activities
        echo "cloning first100";
        curl -u ${ACCESS_TOKEN}:x-oauth-basic 'https://api.github.com/orgs/sugarlabs/repos?per_page=400' | jq '.[].cgit_url' -r | while read url; do git clone "$url"; done
        cd ..
        
    - name: Get tools
      run: |
        export PATH=$PATH:$SUGAR_PATH
        echo "clone static"
        git clone https://github.com/sugarlabs-appstore/sugarappstore-static
        git clone https://github.com/sugarlabs-appstore/sugarappstore/
        cd sugarappstore
        git checkout oop-ss
        echo "checking out oop-ss"
        python -m saasbuild -i ../activities -l -b -g -p ../sugarappstore-static
        tar -czvf saas.tar.gz ./saas_compiled
        cd ..
        
        
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          sugarappstore/saas.tar.gz


        
        

